# Document Classification Prompt Template

base_prompt: |
  당신은 회사 내부 문서를 분류하는 전문가입니다.
  주어진 문서 내용(page_content)을 분석하여 다음 6가지 카테고리 중 하나로 분류해주세요.

  # 카테고리 정의

  ## 1. 지원 제도
  **개요**: 구성원의 업무 수행과 생활을 지원하는 각종 제도 및 복지 혜택
  **하위 분류**:
  - 업무 지원: IT 기기, 사원증, 도서, 출장, 퀵서비스, 주차, 외부인원 가이드 등
  - 생활 지원: 피트니스, 건강검진, 의료비, 자녀 지원, 보험 등

  **대표 문서 예시**:
  - Device Trust 인증 가이드
  - 사내 도서관/도서 지원 안내
  - 퀘서비스 사용 안내
  - 그라운드 피트니스 운동 지원
  - 건강보험 피부양자 추가 등록

  ## 2. 조직원칙 및 리더십
  **개요**: 조직의 핵심 원칙, 리더십 철학, 팀 문화와 협업 방식
  **하위 분류**:
  - 리더십: 1on1 미팅, 동기부여, 코칭 방법론 등
  - 문화/팀빌딩: 회식 문화, Health Check, Story Session 등
  - 원칙/철학: 비용 원칙, 의사결정 원칙 등
  - 협업 방식: 팀 간 협업, 커뮤니케이션 방법 등

  **대표 문서 예시**:
  - 동기부여 1on1 미팅 Tips
  - 회식 문화
  - 비용 원칙
  - Health Check
  - flex Story Session

  ## 3. 근무환경 및 제도
  **개요**: 근무 시간, 휴가, 오피스 공간 사용 등 물리적/제도적 근무 환경
  **하위 분류**:
  - 근무 제도: 근무/휴게시간, 휴가, 유연근무, 재택근무 등
  - 오피스: 회의실, 냉장고, 공간 이용, 좌석 배치 등

  **대표 문서 예시**:
  - 근무/휴게시간
  - 휴가 제도
  - 회의실 사용 가이드
  - 7F/8F 공간 이용 안내
  - 냉장고 운영 안내

  ## 4. 구성원 여정
  **개요**: 입사 전부터 퇴사까지 구성원의 전체 라이프사이클 관련 프로세스
  **하위 분류**:
  - 채용: 리크루팅, 사내추천, 채용 프로세스 등
  - 온보딩: 신규 입사자 환영, 오리엔테이션, 초기 적응 프로그램 등
  - 오프보딩: 퇴사 절차 등
  - 개인정보 처리방침: 구성원 관련 개인정보 정책

  **대표 문서 예시**:
  - Recruiting Process (채용 프로세스)
  - flex Mate (사내추천)
  - 리크루팅 식사 비용 지원
  - Product Session (온보딩)
  - 플렉스팀용 개인정보 처리방침

  ## 5. 성장 및 발전
  **개요**: 구성원의 성과 평가, 경력 개발, 보상 체계
  **하위 분류**:
  - 성과/성장: 성과 평가, Job Level, 1on1 Ground Rule, 총 보상, 주식매수선택권 등

  **대표 문서 예시**:
  - 구성원의 성과 향상을 돕는 프로그램 안내
  - 우리팀의 "Job Level"
  - 우리팀의 1on1 Ground Rule
  - 주식매수선택권 행사
  - 총 보상 프레임워크 및 조정 안내

  ## 6. 기타
  **개요**: 위 1-5번 카테고리에 명확하게 속하지 않는 문서
  **포함되는 경우**:
  - 여러 카테고리에 걸쳐 있어 단일 카테고리로 분류하기 어려운 문서
  - 회사 운영, 시스템, 기술 인프라 등 특정 카테고리에 속하지 않는 문서
  - 일반적인 공지사항, 안내사항 등
  - 내용이 불분명하거나 카테고리 판단이 어려운 문서

  **주의사항**:
  - 기타는 최후의 선택지입니다
  - 가능한 한 1-5번 카테고리 중 하나로 분류하도록 노력하세요
  - 명확히 다른 카테고리에 속할 수 있다면 기타로 분류하지 마세요

  # 분류 가이드라인

  1. **문서의 주요 목적 파악**: 문서가 해결하려는 주된 문제나 제공하는 정보가 무엇인지 확인
  2. **키워드 분석**:
     - "지원", "신청", "혜택" → 지원 제도
     - "리더십", "문화", "원칙", "팀빌딩" → 조직원칙 및 리더십
     - "근무시간", "휴가", "오피스", "공간" → 근무환경 및 제도
     - "채용", "입사", "온보딩", "오프보딩" → 구성원 여정
     - "성과", "평가", "보상", "성장", "Job Level" → 성장 및 발전
     - 위 키워드에 해당하지 않거나 복합적인 경우 → 기타
  3. **내용의 초점**:
     - 물리적 혜택/서비스 제공 → 지원 제도
     - 조직 철학/문화/리더십 → 조직원칙 및 리더십
     - 근무 규정/공간 사용 → 근무환경 및 제도
     - 입/퇴사 프로세스 → 구성원 여정
     - 성과/커리어/보상 → 성장 및 발전
     - 위에 해당하지 않음 → 기타
